//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Jjcu
{
    using System;
    using System.Xml;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Виды карт.
    /// </summary>
    // *** Start programmer edit section *** (ВидыКарт CustomAttributes)

    // *** End programmer edit section *** (ВидыКарт CustomAttributes)
    public enum ВидыКарт
    {
        
        // *** Start programmer edit section *** (ВидыКарт.Универсальная CustomAttributes)

        // *** End programmer edit section *** (ВидыКарт.Универсальная CustomAttributes)
        Универсальная,
        
        // *** Start programmer edit section *** (ВидыКарт.Гостевая CustomAttributes)

        // *** End programmer edit section *** (ВидыКарт.Гостевая CustomAttributes)
        Гостевая,
    }
}
