//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Jjcu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Карты доступа.
    /// </summary>
    // *** Start programmer edit section *** (КартыДоступа CustomAttributes)

    // *** End programmer edit section *** (КартыДоступа CustomAttributes)
    [AutoAltered()]
    [Caption("Карты доступа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("КартыДоступаE", new string[] {
            "КодКарты as \'Код карты\'",
            "ТипКарты as \'Тип карты\'"})]
    [View("КартыДоступаL", new string[] {
            "КодКарты as \'Код карты\'",
            "ТипКарты as \'Тип карты\'"})]
    public class КартыДоступа : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодКарты;
        
        private IIS.Jjcu.ВидыКарт fТипКарты;
        
        // *** Start programmer edit section *** (КартыДоступа CustomMembers)

        // *** End programmer edit section *** (КартыДоступа CustomMembers)

        
        /// <summary>
        /// КодКарты.
        /// </summary>
        // *** Start programmer edit section *** (КартыДоступа.КодКарты CustomAttributes)

        // *** End programmer edit section *** (КартыДоступа.КодКарты CustomAttributes)
        public virtual int КодКарты
        {
            get
            {
                // *** Start programmer edit section *** (КартыДоступа.КодКарты Get start)

                // *** End programmer edit section *** (КартыДоступа.КодКарты Get start)
                int result = this.fКодКарты;
                // *** Start programmer edit section *** (КартыДоступа.КодКарты Get end)

                // *** End programmer edit section *** (КартыДоступа.КодКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартыДоступа.КодКарты Set start)

                // *** End programmer edit section *** (КартыДоступа.КодКарты Set start)
                this.fКодКарты = value;
                // *** Start programmer edit section *** (КартыДоступа.КодКарты Set end)

                // *** End programmer edit section *** (КартыДоступа.КодКарты Set end)
            }
        }
        
        /// <summary>
        /// ТипКарты.
        /// </summary>
        // *** Start programmer edit section *** (КартыДоступа.ТипКарты CustomAttributes)

        // *** End programmer edit section *** (КартыДоступа.ТипКарты CustomAttributes)
        public virtual IIS.Jjcu.ВидыКарт ТипКарты
        {
            get
            {
                // *** Start programmer edit section *** (КартыДоступа.ТипКарты Get start)

                // *** End programmer edit section *** (КартыДоступа.ТипКарты Get start)
                IIS.Jjcu.ВидыКарт result = this.fТипКарты;
                // *** Start programmer edit section *** (КартыДоступа.ТипКарты Get end)

                // *** End programmer edit section *** (КартыДоступа.ТипКарты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (КартыДоступа.ТипКарты Set start)

                // *** End programmer edit section *** (КартыДоступа.ТипКарты Set start)
                this.fТипКарты = value;
                // *** Start programmer edit section *** (КартыДоступа.ТипКарты Set end)

                // *** End programmer edit section *** (КартыДоступа.ТипКарты Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "КартыДоступаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартыДоступаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартыДоступаE", typeof(IIS.Jjcu.КартыДоступа));
                }
            }
            
            /// <summary>
            /// "КартыДоступаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View КартыДоступаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("КартыДоступаL", typeof(IIS.Jjcu.КартыДоступа));
                }
            }
        }
    }
}
