//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Jjcu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Тч рег входа.
    /// </summary>
    // *** Start programmer edit section *** (ТчРегВхода CustomAttributes)

    // *** End programmer edit section *** (ТчРегВхода CustomAttributes)
    [AutoAltered()]
    [Caption("Тч рег входа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТчРегВходаE", new string[] {
            "Гость as \'Гость\'",
            "Гость.Фамилия as \'Фамилия\'",
            "Сотрудник as \'Сотрудник\'",
            "Сотрудник.Фамилия as \'Фамилия\'",
            "КартыДоступа as \'Карты доступа\'",
            "КартыДоступа.КодКарты as \'Код карты\'",
            "Должности as \'Должности\'",
            "Должности.Наименование as \'Наименование\'"}, Hidden=new string[] {
            "Гость.Фамилия",
            "Сотрудник.Фамилия",
            "КартыДоступа.КодКарты",
            "Должности.Наименование"})]
    [MasterViewDefineAttribute("ТчРегВходаE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ТчРегВходаE", "Сотрудник", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [MasterViewDefineAttribute("ТчРегВходаE", "КартыДоступа", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [MasterViewDefineAttribute("ТчРегВходаE", "Должности", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Наименование")]
    public class ТчРегВхода : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Jjcu.Гость fГость;
        
        private IIS.Jjcu.Сотрудник fСотрудник;
        
        private IIS.Jjcu.КартыДоступа fКартыДоступа;
        
        private IIS.Jjcu.Должности fДолжности;
        
        private IIS.Jjcu.ФормаРегВхода fФормаРегВхода;
        
        // *** Start programmer edit section *** (ТчРегВхода CustomMembers)

        // *** End programmer edit section *** (ТчРегВхода CustomMembers)

        
        /// <summary>
        /// Тч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТчРегВхода.Гость CustomAttributes)

        // *** End programmer edit section *** (ТчРегВхода.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Jjcu.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ТчРегВхода.Гость Get start)

                // *** End programmer edit section *** (ТчРегВхода.Гость Get start)
                IIS.Jjcu.Гость result = this.fГость;
                // *** Start programmer edit section *** (ТчРегВхода.Гость Get end)

                // *** End programmer edit section *** (ТчРегВхода.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчРегВхода.Гость Set start)

                // *** End programmer edit section *** (ТчРегВхода.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ТчРегВхода.Гость Set end)

                // *** End programmer edit section *** (ТчРегВхода.Гость Set end)
            }
        }
        
        /// <summary>
        /// Тч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТчРегВхода.Должности CustomAttributes)

        // *** End programmer edit section *** (ТчРегВхода.Должности CustomAttributes)
        [PropertyStorage(new string[] {
                "Должности"})]
        [NotNull()]
        public virtual IIS.Jjcu.Должности Должности
        {
            get
            {
                // *** Start programmer edit section *** (ТчРегВхода.Должности Get start)

                // *** End programmer edit section *** (ТчРегВхода.Должности Get start)
                IIS.Jjcu.Должности result = this.fДолжности;
                // *** Start programmer edit section *** (ТчРегВхода.Должности Get end)

                // *** End programmer edit section *** (ТчРегВхода.Должности Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчРегВхода.Должности Set start)

                // *** End programmer edit section *** (ТчРегВхода.Должности Set start)
                this.fДолжности = value;
                // *** Start programmer edit section *** (ТчРегВхода.Должности Set end)

                // *** End programmer edit section *** (ТчРегВхода.Должности Set end)
            }
        }
        
        /// <summary>
        /// Тч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТчРегВхода.КартыДоступа CustomAttributes)

        // *** End programmer edit section *** (ТчРегВхода.КартыДоступа CustomAttributes)
        [PropertyStorage(new string[] {
                "КартыДоступа"})]
        [NotNull()]
        public virtual IIS.Jjcu.КартыДоступа КартыДоступа
        {
            get
            {
                // *** Start programmer edit section *** (ТчРегВхода.КартыДоступа Get start)

                // *** End programmer edit section *** (ТчРегВхода.КартыДоступа Get start)
                IIS.Jjcu.КартыДоступа result = this.fКартыДоступа;
                // *** Start programmer edit section *** (ТчРегВхода.КартыДоступа Get end)

                // *** End programmer edit section *** (ТчРегВхода.КартыДоступа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчРегВхода.КартыДоступа Set start)

                // *** End programmer edit section *** (ТчРегВхода.КартыДоступа Set start)
                this.fКартыДоступа = value;
                // *** Start programmer edit section *** (ТчРегВхода.КартыДоступа Set end)

                // *** End programmer edit section *** (ТчРегВхода.КартыДоступа Set end)
            }
        }
        
        /// <summary>
        /// Тч рег входа.
        /// </summary>
        // *** Start programmer edit section *** (ТчРегВхода.Сотрудник CustomAttributes)

        // *** End programmer edit section *** (ТчРегВхода.Сотрудник CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудник"})]
        [NotNull()]
        public virtual IIS.Jjcu.Сотрудник Сотрудник
        {
            get
            {
                // *** Start programmer edit section *** (ТчРегВхода.Сотрудник Get start)

                // *** End programmer edit section *** (ТчРегВхода.Сотрудник Get start)
                IIS.Jjcu.Сотрудник result = this.fСотрудник;
                // *** Start programmer edit section *** (ТчРегВхода.Сотрудник Get end)

                // *** End programmer edit section *** (ТчРегВхода.Сотрудник Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчРегВхода.Сотрудник Set start)

                // *** End programmer edit section *** (ТчРегВхода.Сотрудник Set start)
                this.fСотрудник = value;
                // *** Start programmer edit section *** (ТчРегВхода.Сотрудник Set end)

                // *** End programmer edit section *** (ТчРегВхода.Сотрудник Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Jjcu.ФормаРегВхода.
        /// </summary>
        // *** Start programmer edit section *** (ТчРегВхода.ФормаРегВхода CustomAttributes)

        // *** End programmer edit section *** (ТчРегВхода.ФормаРегВхода CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ФормаРегВхода"})]
        public virtual IIS.Jjcu.ФормаРегВхода ФормаРегВхода
        {
            get
            {
                // *** Start programmer edit section *** (ТчРегВхода.ФормаРегВхода Get start)

                // *** End programmer edit section *** (ТчРегВхода.ФормаРегВхода Get start)
                IIS.Jjcu.ФормаРегВхода result = this.fФормаРегВхода;
                // *** Start programmer edit section *** (ТчРегВхода.ФормаРегВхода Get end)

                // *** End programmer edit section *** (ТчРегВхода.ФормаРегВхода Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТчРегВхода.ФормаРегВхода Set start)

                // *** End programmer edit section *** (ТчРегВхода.ФормаРегВхода Set start)
                this.fФормаРегВхода = value;
                // *** Start programmer edit section *** (ТчРегВхода.ФормаРегВхода Set end)

                // *** End programmer edit section *** (ТчРегВхода.ФормаРегВхода Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТчРегВходаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТчРегВходаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТчРегВходаE", typeof(IIS.Jjcu.ТчРегВхода));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТчРегВхода.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТчРегВхода CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТчРегВхода CustomAttributes)
    public class DetailArrayOfТчРегВхода : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Jjcu.DetailArrayOfТчРегВхода members)

        // *** End programmer edit section *** (IIS.Jjcu.DetailArrayOfТчРегВхода members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТчРегВхода by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТчРегВхода.
        /// </summary>
        public DetailArrayOfТчРегВхода(IIS.Jjcu.ФормаРегВхода fФормаРегВхода) : 
                base(typeof(ТчРегВхода), ((ICSSoft.STORMNET.DataObject)(fФормаРегВхода)))
        {
        }
        
        public IIS.Jjcu.ТчРегВхода this[int index]
        {
            get
            {
                return ((IIS.Jjcu.ТчРегВхода)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Jjcu.ТчРегВхода dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
