//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Jjcu
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Форма рег карт.
    /// </summary>
    // *** Start programmer edit section *** (ФормаРегКарт CustomAttributes)

    // *** End programmer edit section *** (ФормаРегКарт CustomAttributes)
    [AutoAltered()]
    [Caption("Форма рег карт")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ФормаРегКартE", new string[] {
            "Комната as \'Комната\'",
            "Комната.Номер as \'Номер\'",
            "КартыДоступа as \'Карты доступа\'",
            "КартыДоступа.КодКарты as \'Код карты\'",
            "Гость as \'Гость\'",
            "Гость.Фамилия as \'Фамилия\'"}, Hidden=new string[] {
            "Комната.Номер",
            "КартыДоступа.КодКарты",
            "Гость.Фамилия"})]
    [MasterViewDefineAttribute("ФормаРегКартE", "Комната", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номер")]
    [MasterViewDefineAttribute("ФормаРегКартE", "КартыДоступа", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "КодКарты")]
    [MasterViewDefineAttribute("ФормаРегКартE", "Гость", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Фамилия")]
    [View("ФормаРегКартL", new string[] {
            "Комната.Номер as \'Номер\'",
            "КартыДоступа.КодКарты as \'Код карты\'",
            "Гость.Фамилия as \'Фамилия\'"})]
    public class ФормаРегКарт : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Jjcu.Комната fКомната;
        
        private IIS.Jjcu.КартыДоступа fКартыДоступа;
        
        private IIS.Jjcu.Гость fГость;
        
        // *** Start programmer edit section *** (ФормаРегКарт CustomMembers)

        // *** End programmer edit section *** (ФормаРегКарт CustomMembers)

        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Гость CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Гость CustomAttributes)
        [PropertyStorage(new string[] {
                "Гость"})]
        [NotNull()]
        public virtual IIS.Jjcu.Гость Гость
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Get start)
                IIS.Jjcu.Гость result = this.fГость;
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Set start)
                this.fГость = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Гость Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Гость Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.КартыДоступа CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.КартыДоступа CustomAttributes)
        [PropertyStorage(new string[] {
                "КартыДоступа"})]
        [NotNull()]
        public virtual IIS.Jjcu.КартыДоступа КартыДоступа
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.КартыДоступа Get start)

                // *** End programmer edit section *** (ФормаРегКарт.КартыДоступа Get start)
                IIS.Jjcu.КартыДоступа result = this.fКартыДоступа;
                // *** Start programmer edit section *** (ФормаРегКарт.КартыДоступа Get end)

                // *** End programmer edit section *** (ФормаРегКарт.КартыДоступа Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.КартыДоступа Set start)

                // *** End programmer edit section *** (ФормаРегКарт.КартыДоступа Set start)
                this.fКартыДоступа = value;
                // *** Start programmer edit section *** (ФормаРегКарт.КартыДоступа Set end)

                // *** End programmer edit section *** (ФормаРегКарт.КартыДоступа Set end)
            }
        }
        
        /// <summary>
        /// Форма рег карт.
        /// </summary>
        // *** Start programmer edit section *** (ФормаРегКарт.Комната CustomAttributes)

        // *** End programmer edit section *** (ФормаРегКарт.Комната CustomAttributes)
        [PropertyStorage(new string[] {
                "Комната"})]
        [NotNull()]
        public virtual IIS.Jjcu.Комната Комната
        {
            get
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Get start)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Get start)
                IIS.Jjcu.Комната result = this.fКомната;
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Get end)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Set start)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Set start)
                this.fКомната = value;
                // *** Start programmer edit section *** (ФормаРегКарт.Комната Set end)

                // *** End programmer edit section *** (ФормаРегКарт.Комната Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ФормаРегКартE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегКартE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегКартE", typeof(IIS.Jjcu.ФормаРегКарт));
                }
            }
            
            /// <summary>
            /// "ФормаРегКартL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ФормаРегКартL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ФормаРегКартL", typeof(IIS.Jjcu.ФормаРегКарт));
                }
            }
        }
    }
}
